### ISSUE TITLE
Pubsub: client pull ignoring KeyboardInterrupt

### ISSUE THREAD

**Issue by jjhuff** [googleapis/python-pubsub#17]
Pubsub/grpc seem to ignore `KeyboardInterrupt` while blocked on a client.pull. Then you end up with a `KeyError`. Seems like it'd be better to let the KeyboardInterrupt propagate up.

Python 3.5.7 on a Debian stretch Docker container
google-api-core==1.9.0
google-auth==1.6.3
google-cloud-core==0.29.1
google-cloud-pubsub==0.40.0
google-cloud-storage==1.14.0
google-resumable-media==0.3.2
googleapis-common-protos==1.5.9
grpc-google-iam-v1==0.11.4

#### Code example
```python
        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
            not_done = set()
            while True:
                if len(not_done) < batch_size/2:
                    try:
                        resp = self._subscriber_client.pull(self._subscription, max_messages=batch_size)
                        LOG.debug("Got: {}".format(len(resp.received_messages)))

                        for msg in resp.received_messages:
                            not_done.add(executor.submit(message_callback, msg.ack_id, msg.message))
                    except google.api_core.exceptions.DeadlineExceeded:
                        # Nothing in the queue, but keep trying
                        pass
                    except google.api_core.exceptions.RetryError:
                        pass
                    except KeyboardInterrupt:
                        print("!!!!!!!!!!!");
                        break
                    except Exception as e:
                        LOG.error(traceback.format_exc())
```

#### Log/backtrace
```
^CKeyboardInterrupt
Exception ignored in: 'grpc._cython.cygrpc._next'
KeyboardInterrupt
ERROR:amplion.utils.pubsub_queue:Traceback (most recent call last):
  File "/app/amplion/utils/pubsub_queue.py", line 108, in listen
    resp = self._subscriber_client.pull(self._subscription, max_messages=batch_size)
  File "/usr/local/lib/python3.5/site-packages/google/cloud/pubsub_v1/_gapic.py", line 45, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/usr/local/lib/python3.5/site-packages/google/cloud/pubsub_v1/gapic/subscriber_client.py", line 864, in pull
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.5/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.5/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/usr/local/lib/python3.5/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 548, in __call__
    wait_for_ready)
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 537, in _blocking
    event = call.next_event()
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 310, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 151, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 152, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 308, in grpc._cython.cygrpc.SegregatedCall.next_event.on_success
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 282, in grpc._cython.cygrpc._process_segregated_call_tag
KeyError: None

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by gbattra** [comment]
i am experiencing this bug as well. implemented a similar approach to @plamut but no luck:
`def consume():
    try:
        subscriber = pubsub_v1.SubscriberClient()
        subscription_path = 'projects/sylvan-terra-269023/subscriptions/new-painter-request-pull'

        # subscriber.create_subscription(subscription_path, topic=TOPIC_NAME)

        def callback(message):
            try:
                # data = json.loads(message.data.decode('utf-8'))
                print(message.data.decode('utf-8'))
                # engine.paint('https://i.imgur.com/oZ67OF4.jpg')
                message.ack()
            except ValueError:
                raise

        future = subscriber.subscribe(subscription_path, callback=callback)

        try:
            future.result()
        except KeyboardInterrupt:
            future.cancel()
    except KeyboardInterrupt:
        raise


if __name__ == '__main__':
    try:
        consume()
    except Exception:
        exit(1)`

**Comment by gbattra** [comment]
i am experiencing this bug as well. implemented a similar approach to @plamut but no luck:
```
def consume():
    try:
        subscriber = pubsub_v1.SubscriberClient()
        subscription_path = 'projects/sylvan-terra-269023/subscriptions/new-painter-request-pull'

        # subscriber.create_subscription(subscription_path, topic=TOPIC_NAME)

        def callback(message):
            try:
                print(message.data.decode('utf-8'))
                message.ack()
            except ValueError:
                raise

        future = subscriber.subscribe(subscription_path, callback=callback)

        try:
            future.result()
        except KeyboardInterrupt:
            future.cancel()
    except KeyboardInterrupt:
        raise


if __name__ == '__main__':
    try:
        consume()
    except Exception:
        exit(1)
```

**Comment by gbattra** [comment]
i am experiencing this bug as well. implemented a similar approach to @plamut but no luck:
```
def consume():
    try:
        subscriber = pubsub_v1.SubscriberClient()

        def callback(message):
            try:
                print(message.data.decode('utf-8'))
                message.ack()
            except ValueError:
                raise

        future = subscriber.subscribe(SUBSCRIPTION_PATH, callback=callback)

        try:
            future.result()
        except KeyboardInterrupt:
            future.cancel()
    except KeyboardInterrupt:
        raise


if __name__ == '__main__':
    try:
        consume()
    except Exception:
        exit(1)
```

**Comment by plamut** [comment]
@gbattra Which Python/grpcio versions did you use? Are your findings consistent with mine posted above, or did you actually reproduce the bug in Python 3.x?

**Comment by gbattra** [comment]
i'm using python 3.7. running the file as a script

**Comment by plamut** [comment]
Interesting, as I was not able to reproduce the issue on Python 3.7 and `grpcio==1.27.2` (on Ubuntu 18.04, if it matters).

**Comment by pradn** [comment]
@gbattra Can you tell us your Python version, GRPC version and your OS version, please?

**Comment by meredithslota** [comment]
@gbattra We have been unable to reproduce this issue — if you are still seeing this, and are able to provide repro details including the questions above, please feel free to reopen! Thanks! :)

**Comment by galah92** [comment]
Hi, I'm getting the exact same thing as @gbattra did - `KeyboardInterrupt` isn't firing. Using Python v3.8.3 and `grpcio` v1.33.1 on Windows 10.
