### ISSUE TITLE
Can not import module after upgrade

### ISSUE THREAD

**Issue by frankShih** [googleapis/python-pubsub#183]
#### Environment details

  - OS type and version: win10
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-pubsub` version: `pip show google-cloud-pubsub`

#### Steps to reproduce

  1. update `google-cloud-pubsub` from 0.39.1 to 1.7.0
  2. follow the instructions in "README"

#### Code example

```python
# from google.cloud import pubsub_v1
```

#### Stack trace
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\types.py", line 32, in <module>
    from google.cloud.pubsub_v1.proto import pubsub_pb2
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\proto\pubsub_pb2.py", line 30, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
>>> from google.cloud import pubsub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub.py", line 20, in <module>
    from google.cloud.pubsub_v1 import PublisherClient
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\types.py", line 32, in <module>
    from google.cloud.pubsub_v1.proto import pubsub_pb2
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\proto\pubsub_pb2.py", line 30, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

Unsure what happened, maybe the conflict between different versions of dependencies?
```shell
pip freeze | grep 'google'
Line       : google-api-core==1.14.3
Line       : google-api-python-client==1.7.1
Line       : google-apitools==0.5.28
Line       : google-auth==1.14.1
Line       : google-auth-httplib2==0.0.4
Line       : google-auth-oauthlib==0.4.1
Line       : google-cloud-bigquery==1.17.1
Line       : google-cloud-bigtable==0.32.2
Line       : google-cloud-core==1.0.3
Line       : google-cloud-datastore==1.7.4
Line       : google-cloud-error-reporting==0.30.0
Line       : google-cloud-logging==1.11.0
Line       : google-cloud-pubsub==1.7.0
Line       : google-cloud-scheduler==1.3.0
Line       : google-cloud-storage==1.20.0
Line       : google-pasta==0.2.0
Line       : google-resumable-media==0.4.1
Line       : googleapis-common-protos==1.6.0
Line       : grpc-google-iam-v1==0.12.3
```

Any suggestion would be appreciated, thanks in prior.

**Comment by HemangChothani** [comment]
@frankShih Could you please share the version of `protobuf`

**Comment by HemangChothani** [comment]
@frankShih Please also update following libraries:

- google-api-core
- google-cloud-core
- googleapis-common-protos
- google-auth
- protobuf

**Comment by frankShih** [comment]
> @frankShih Could you please share the version of `protobuf`

Thanks for your help. Here is the info:
```shell
Name: protobuf
Version: 3.11.4
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
```

After I execute 
`pip3 install google-api-core google-cloud-core googleapis-common-protos google-auth protobuf --upgrade --use-feature=2020-resolver`

A new error occurred
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\__init__.py", line 18, in <module>
    from google.cloud.pubsub_v1 import publisher
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\publisher\__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1.publisher.client import Client
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\publisher\client.py", line 32, in <module>
    from google.cloud.pubsub_v1.gapic import publisher_client
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\cloud\pubsub_v1\gapic\publisher_client.py", line 28, in <module>
    import google.api_core.gapic_v1.client_info
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\api_core\gapic_v1\__init__.py", line 26, in <module>
    from google.api_core.gapic_v1 import method_async  # noqa: F401
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\api_core\gapic_v1\method_async.py", line 20, in <module>
    from google.api_core import general_helpers, grpc_helpers_async
  File "C:\ProgramData\Miniconda3\lib\site-packages\google\api_core\grpc_helpers_async.py", line 145, in <module>
    class _WrappedStreamUnaryCall(_WrappedUnaryResponseMixin, _WrappedStreamRequestMixin, aio.StreamUnaryCall):
AttributeError: module 'grpc.experimental.aio' has no attribute 'StreamUnaryCall'
```

Package version info is here:
```shell
Line       : google-api-core==1.22.2
Line       : google-api-python-client==1.7.1
Line       : google-apitools==0.5.28
Line       : google-auth==1.21.1
Line       : google-auth-httplib2==0.0.4
Line       : google-auth-oauthlib==0.4.1
Line       : google-cloud-bigquery==1.17.1
Line       : google-cloud-bigtable==0.32.2
Line       : google-cloud-core==1.4.1
Line       : google-cloud-datastore==1.7.4
Line       : google-cloud-error-reporting==0.30.0
Line       : google-cloud-logging==1.11.0
Line       : google-cloud-pubsub==1.7.0
Line       : google-cloud-scheduler==1.3.0
Line       : google-cloud-storage==1.20.0
Line       : google-pasta==0.2.0
Line       : google-resumable-media==0.4.1
Line       : googleapis-common-protos==1.52.0
Line       : grpc-google-iam-v1==0.12.3
Line       : protobuf==3.13.0
```

Should I just remove all related libraries & reinstall it? (I am not sure how to "completely" remove it.

**Comment by HemangChothani** [comment]
@frankShih Also need to upgrade the `grpcio` library, because as i can see in the extras of `google-api-core` requirements [here](https://github.com/googleapis/python-api-core/blob/11d2097b9c125201244836261ae8068a32553586/setup.py#L41-L42), it supports the ` grpcio >=1.29.0` .
