### ISSUE TITLE
Error while importing: from google.cloud import pubsub_v1

### ISSUE THREAD

**Issue by becks-ddf** [googleapis/python-pubsub#261]
`from google.cloud import pubsub_v1`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/google/cloud/pubsub_v1/types.py", line 36, in <module>
    from google.pubsub_v1.types import pubsub as pubsub_gapic_types
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/google/pubsub_v1/__init__.py", line 18, in <module>
    from .services.publisher import PublisherClient
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/google/pubsub_v1/services/publisher/__init__.py", line 18, in <module>
    from .client import PublisherClient
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/google/pubsub_v1/services/publisher/client.py", line 37, in <module>
    from google.pubsub_v1.services.publisher import pagers
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/google/pubsub_v1/services/publisher/pagers.py", line 20, in <module>
    from google.pubsub_v1.types import pubsub
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/google/pubsub_v1/types/__init__.py", line 18, in <module>
    from .pubsub import (
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/google/pubsub_v1/types/pubsub.py", line 76, in <module>
    class MessageStoragePolicy(proto.Message):
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/proto/message.py", line 214, in __new__
    field=[i.descriptor for i in fields],
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/proto/message.py", line 214, in <listcomp>
    field=[i.descriptor for i in fields],
  File "/home/becks_ddf/my_env/lib/python3.8/site-packages/proto/fields.py", line 104, in descriptor
    self._descriptor = descriptor_pb2.FieldDescriptorProto(
ValueError: Protocol message FieldDescriptorProto has no "proto3_optional" field.

Output of `pip freeze` looks:
apt-clone==0.2.1
apturl==0.5.2
beautifulsoup4==4.8.2
blinker==1.4
Brlapi==0.7.0
cachetools==4.2.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
distro==1.4.0
entrypoints==0.3
google-api-core==1.24.1
google-auth==1.24.0
google-cloud-pubsub==2.2.0
googleapis-common-protos==1.52.0
grpc-google-iam-v1==0.12.3
grpcio==1.34.0
httplib2==0.14.0
idna==2.8
ifaddr==0.1.6
keyring==18.0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
libcst==0.3.16
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.0
MarkupSafe==1.1.0
mypy-extensions==0.4.3
netifaces==0.10.4
nose==1.3.7
oauthlib==3.1.0
onboard==1.4.1
packaging==20.3
PAM==0.4.2
pexpect==4.6.0
Pillow==7.0.0
proto-plus==1.13.0
protobuf==3.14.0
psutil==5.5.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.2
PyGObject==3.36.0
PyICU==2.4.2
pyinotify==0.9.6
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyparsing==2.4.6
pyparted==3.11.2
pyRFC3339==1.1
python-apt==2.0.0+ubuntu0.20.4.2
python-debian===0.1.36ubuntu1
python-xapp==2.0.1
python-xlib==0.23
pytz==2019.3
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
rsa==4.6
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
setproctitle==1.1.10
simplejson==3.16.0
six==1.14.0
soupsieve==1.9.5
systemd-python==234
tinycss2==1.0.2
typing-extensions==3.7.4.3
typing-inspect==0.6.0
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
Unidecode==1.1.1
urllib3==1.25.8
wadllib==1.3.3
webencodings==0.5.1
xkit==0.0.0
zeroconf==0.24.4

**Comment by HemangChothani** [comment]
@becks-ddf Able to reproduce the error only when  version `protobuf<=3.11.0`
Please try to check the version of protobuf at the runtime.

```python
import pkg_resources
pkg_resources.get_distribution("protobuf").parsed_version    #print protobuf used version at the runtime.

**Comment by plamut** [comment]
@becks-ddf Did you manage to resolve the issue by upgrading? Thanks!

**Comment by plamut** [comment]
Closing due to inactivity and because upgrading the dependencies fixes the problem.

@becks-ddf Should you still experience problems even upgrading, feel free to come back and re-open the issue.

**Comment by abarberenaCPDS** [comment]
Hi @plamut, I just found this thread about a similar problem that I have.

I can provide more details if needed.

I am trying to run the steps in this tutorial from Google
  - https://cloud.google.com/pubsub/docs/publish-receive-messages-client-library

I am using a RaspberryPI with an aarch64 centos:

```bash
uname -a
Linux centospi 5.4.72-v8.1.el7 #1 SMP PREEMPT Wed Oct 21 17:35:36 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

And this is the error trying to run the sample code:

``` bash
(dev) ➜  ~ python dev-py/pubsub.py
Traceback (most recent call last):
  File "dev-py/pubsub.py", line 1, in <module>
    from google.cloud import pubsub_v1
  File "/root/dev/lib/python3.6/site-packages/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/root/dev/lib/python3.6/site-packages/google/cloud/pubsub_v1/types.py", line 28, in <module>
    from google.iam.v1 import iam_policy_pb2  # type: ignore
  File "/root/dev/lib/python3.6/site-packages/google/iam/v1/iam_policy_pb2.py", line 36, in <module>
    from google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2
  File "/root/dev/lib/python3.6/site-packages/google/iam/v1/policy_pb2.py", line 35, in <module>
    b'\n\x1agoogle/iam/v1/policy.proto\x12\rgoogle.iam.v1\x1a\x16google/type/expr.proto"\x84\x01\n\x06Policy\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12(\n\x08\x62indings\x18\x04 \x03(\x0b\x32\x16.google.iam.v1.Binding\x12\x31\n\raudit_configs\x18\x06 \x03(\x0b\x32\x1a.google.iam.v1.AuditConfig\x12\x0c\n\x04\x65tag\x18\x03 \x01(\x0c"N\n\x07\x42inding\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07members\x18\x02 \x03(\t\x12$\n\tcondition\x18\x03 \x01(\x0b\x32\x11.google.type.Expr"X\n\x0b\x41uditConfig\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x38\n\x11\x61udit_log_configs\x18\x03 \x03(\x0b\x32\x1d.google.iam.v1.AuditLogConfig"\xb7\x01\n\x0e\x41uditLogConfig\x12\x37\n\x08log_type\x18\x01 \x01(\x0e\x32%.google.iam.v1.AuditLogConfig.LogType\x12\x18\n\x10\x65xempted_members\x18\x02 \x03(\t"R\n\x07LogType\x12\x18\n\x14LOG_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n\nADMIN_READ\x10\x01\x12\x0e\n\nDATA_WRITE\x10\x02\x12\r\n\tDATA_READ\x10\x03"\x80\x01\n\x0bPolicyDelta\x12\x33\n\x0e\x62inding_deltas\x18\x01 \x03(\x0b\x32\x1b.google.iam.v1.BindingDelta\x12<\n\x13\x61udit_config_deltas\x18\x02 \x03(\x0b\x32\x1f.google.iam.v1.AuditConfigDelta"\xbd\x01\n\x0c\x42indingDelta\x12\x32\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32".google.iam.v1.BindingDelta.Action\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0e\n\x06member\x18\x03 \x01(\t\x12$\n\tcondition\x18\x04 \x01(\x0b\x32\x11.google.type.Expr"5\n\x06\x41\x63tion\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\n\n\x06REMOVE\x10\x02"\xbd\x01\n\x10\x41uditConfigDelta\x12\x36\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32&.google.iam.v1.AuditConfigDelta.Action\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x17\n\x0f\x65xempted_member\x18\x03 \x01(\t\x12\x10\n\x08log_type\x18\x04 \x01(\t"5\n\x06\x41\x63tion\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\n\n\x06REMOVE\x10\x02\x42\x83\x01\n\x11\x63om.google.iam.v1B\x0bPolicyProtoP\x01Z0google.golang.org/genproto/googleapis/iam/v1;iam\xf8\x01\x01\xaa\x02\x13Google.Cloud.Iam.V1\xca\x02\x13Google\\Cloud\\Iam\\V1b\x06proto3'
  File "/root/dev/lib/python3.6/site-packages/google/protobuf/descriptor_pool.py", line 219, in AddSerializedFile
    file_desc = self._ConvertFileProtoToFileDescriptor(file_desc_proto)
  File "/root/dev/lib/python3.6/site-packages/google/protobuf/descriptor_pool.py", line 746, in _ConvertFileProtoToFileDescriptor
    built_deps = list(self._GetDeps(file_proto.dependency))
  File "/root/dev/lib/python3.6/site-packages/google/protobuf/descriptor_pool.py", line 1247, in _GetDeps
    dep_desc = self.FindFileByName(dependency)
  File "/root/dev/lib/python3.6/site-packages/google/protobuf/descriptor_pool.py", line 420, in FindFileByName
    raise error
  File "/root/dev/lib/python3.6/site-packages/google/protobuf/descriptor_pool.py", line 415, in FindFileByName
    file_proto = self._internal_db.FindFileByName(file_name)
  File "/root/dev/lib/python3.6/site-packages/google/protobuf/descriptor_database.py", line 104, in FindFileByName
    return self._file_desc_protos_by_file[name]
KeyError: 'google/type/expr.proto'
```

These are my venv versions:

```bash
(dev) ➜  ~ python --version
Python 3.6.8
(dev) ➜  ~ pip --version
pip 21.3.1 from /root/dev/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by plamut** [comment]
@abarberenaCPDS As of 2022 I do not maintain this library anymore, and thus do not have that good an insight into it.

I suggest opening a new issue for better visibility, and I'm sure someone will take over and try to help with your problem.

cc: @pradn @acocuzzo
