### ISSUE TITLE
502:Bad Gateway when streaming data 

### ISSUE THREAD

**Issue by BarisicLuka** [googleapis/python-pubsub#752]
Hello everyone,

### Problem
I am using PubSub to collect messages from several devices into a topic. I have several subscription attached to this topic including one which is in PULL mode.

The service pulling messages from this subscription is a python backend using the following : 

  - Debian GNU/Linux 10 (buster)
  - Python version: Python 3.7.3
  - pip version: pip 21.3.1
  - `google-cloud-pubsub` version: 2.9.0

There is only one backend pulling data from the subscription and it has been running pretty smoothly until a couple of weeks ago. 3 Weeks ago I started to notice that the connexion to the PubSub service ran into the same issue and causes the process to stop. I added a clause to restart the process after 5 minutes but it fails to be executed.

Here is the trace : 

```python

Traceback (most recent call last):
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/.../venv/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/.../venv/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "502:Bad Gateway"
	debug_error_string = "{"created":"@1659438499.807527343","description":"Error received from peer ipv4:108.177.15.95:443","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"502:Bad Gateway","grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/.../python3.7/site-packages/google/api_core/grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 502:Bad Gateway

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../backend/pubsub.py", line 117, in start_pubsub_streaming
    pubsub_pulling_thread.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 733, in _on_response
    self._dispatcher.modify_ack_deadline(items)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 203, in modify_ack_deadline
    self._manager.send(request)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 470, in send
    self._send_unary_request(request)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 458, in _send_unary_request
    ack_deadline_seconds=deadline,
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/_gapic.py", line 43, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/home/.../venv/lib/python3.7/site-packages/google/pubsub_v1/services/subscriber/client.py", line 936, in modify_ack_deadline
    request, retry=retry, timeout=timeout, metadata=metadata,
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 210, in retry_target
    ) from last_exc
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 502:Bad Gateway


```

From what I understand it appears that the client suddenly has problems connecting to the PubSub service and receives a 502: Bad Gateway error. The thing is that it can happen once but it appears at least once a day and without a clear patter.

I don't know what causes this error to appear I dont see any memory or CPU problems with the machine so it's pretty hard to give you steps to reproduce. However here is the code that I use to initialize the connexion 

#### Code example

`pubsub.py`
```python
import json
import time
from datetime import datetime
from typing import List
import logging

from concurrent.futures import TimeoutError
from google.cloud import pubsub_v1
from google.oauth2 import service_account

from backend.core.config import PUBSUB_SUB_ID, GCP_PROJECT_ID, SERVICE_ACCOUNT_CREDENTIALS, FIRESTORE_INTERFACE
from backend.transitions_database import DATABASE

_LOGGER = logging.getLogger(__name__)

# Loading  service account credentials
with open(SERVICE_ACCOUNT_CREDENTIALS, 'r') as f:
    info = eval(f.read())
_SCOPE = 'https://www.googleapis.com/auth/pubsub'
_CREDENTIALS = service_account.Credentials.from_service_account_info(
    info, scopes=(_SCOPE,))

# Connecting to the subscription
_SUBSCRIBER = pubsub_v1.SubscriberClient(credentials=_CREDENTIALS)
SUBSCRIPTION_PATH = _SUBSCRIBER.subscription_path(GCP_PROJECT_ID, PUBSUB_SUB_ID)


def shape_inference_messages(message: pubsub_v1.subscriber.message.Message) -> List[]:
    """

    Parameters
    ----------
    message: pubsub_v1.subscriber.message.Message

    """
    ....
    processes the messages
    ....
    return inferences


def store_messages(message: pubsub_v1.subscriber.message.Message) -> None:
    """
    Callback function used on every PubSub message received. Extract and shape
    inferences from the message and insert it in the database buffer.
    If no exception arises acknowledges the message.

    Parameters
    ----------
    message: pubsub_v1.subscriber.message.Message
    """
    # Using global variable so we dont have to add arguments to the callback
    try:
        inferences = shape_inference_messages(message)
        DATABASE.store_inferences(inferences)
        message.ack()
    except Exception as e:
        _LOGGER.error("Message : {message} not processed see following trace")
        _LOGGER.error(e, exc_info=True)
        message.nack()


def create_pubsub_streaming_object():
    """ Create an asynchronous PubSub streaming thread"""
    # Limit the subscriber to only have ten outstanding messages at a time.
    flow_control = pubsub_v1.types.FlowControl(max_messages=10)
    streaming_pull_future = _SUBSCRIBER.subscribe(
        SUBSCRIPTION_PATH,
        callback=store_messages,
        flow_control=flow_control
    )
    return streaming_pull_future


def start_pubsub_streaming(pubsub_pulling_thread):
    """
    Start the streaming thread. If an exception arises then stop the
    streaming it
    """
    try:
        # When `timeout` is not set, result() will block indefinitely,
        # unless an exception is encountered first.
        _LOGGER.info(f"Starting streaming process")
        pubsub_pulling_thread.result()
        _LOGGER.info(f"Listening for messages on {SUBSCRIPTION_PATH}..\n")
    except Exception as e:
        _LOGGER.warning('Exception raised while pulling data, see below', exc_info=True)
        stop_pubsub_streaming(pubsub_pulling_thread)
    finally :
        DATABASE.save_db_state(f'./data/exits/recovery_{datetime.now()}.csv')
        _LOGGER.info(f"Sleeping for 5 minutes before restarting the streaming")
        time.sleep(60*5)
        _LOGGER.info(f"Proceeding to streaming restart")
        start_pubsub_streaming(pubsub_pulling_thread)


def stop_pubsub_streaming(pubsub_pulling_thread):
    """ Stops the streaming thread """
    _LOGGER.info('Stopping the streaming process ...')
    pubsub_pulling_thread.cancel()  # Trigger the shutdown.
    pubsub_pulling_thread.result()  # Block until the shutdown is complete.
    _LOGGER.info('Streaming process stoped.')

```
`__init__.py`

```python3
import backend.transitions_database
from datetime import datetime
from schedule import every, repeat, run_pending

from backend.pubsub import create_pubsub_streaming_object, stop_pubsub_streaming, start_pubsub_streaming
from backend.helpers import *
from backend.transitions_database import DATABASE
from backend.core.config import INFERENCE_BUFFER_TTL

_LOGGER = logging.getLogger(__name__)

# Must be declared now for it to be handled as a global variables in several
# thread handling functions
_PUBSUB_STREAMING_THREAD = threading.Thread(target=lambda x: None)
_PUBSUB_STREAMING_OBJECT = None


@repeat(every(6).hours.at(":00"))
def save_checkpoint(database=DATABASE) -> None:
    """ Saving the DB state every hour """
    database.save_db_state(f'./data/checkpoints/checkpoint_{datetime.now()}.csv')


@repeat(every(INFERENCE_BUFFER_TTL).minutes.at(":00"))
def insert_buffered_inferences(database=DATABASE) -> None:
    """ Saving the DB state every hour """
    database.insert_buffered_inferences()


@repeat(every().day.at("01:15"))
def purge_database(database = DATABASE) -> None:
    """
    Function that stops the pulling process, purges irrelevant
    data and resume the pulling process.
    Repeat decorator is used to execute this function every day at 1 AM.
    """
    global _PUBSUB_STREAMING_THREAD
    stop_pubsub_streaming(_PUBSUB_STREAMING_OBJECT)
    try:
        database.purge_data()
    except Exception as e:
        _LOGGER.error('There has been an error while purging the database', exc_info=True)
    # Whether the purge worked or not, resuming the streaming
    finally:
        _PUBSUB_STREAMING_THREAD = create_pubsub_streaming_thread()
        _PUBSUB_STREAMING_THREAD.start()


def create_pubsub_streaming_thread() -> threading.Thread:
    """
    Create the PubSub streaming object and affects it to the global variable
    defined for this purpose. Also create a thread used to use the streaming
    object.

    Returns
    -------
    thread: threading.Thread
    """
    # Creating the streaming object
    global _PUBSUB_STREAMING_OBJECT
    _PUBSUB_STREAMING_OBJECT = create_pubsub_streaming_object()
    # Creating the streaming thread
    pull_thread = threading.Thread(
        target=start_pubsub_streaming,
        args=[_PUBSUB_STREAMING_OBJECT]
    )
    pull_thread.daemon = True
    pull_thread.name = 'Data pulling thread'
    return pull_thread


def stop_pulling_data(pubsub_streaming_object=_PUBSUB_STREAMING_OBJECT) -> None:
    """
    Stops the PubSub streaming process and kills the associated thread.
    """
    global _PUBSUB_STREAMING_THREAD
    stop_pubsub_streaming(pubsub_streaming_object)
    _PUBSUB_STREAMING_THREAD.join()


def run_backend() -> None:
    """
    Main backend function that spawns several threads to run the PubSub
    streaming as well as the.
    If an exception stops the backend, automatically kills all threads and save
    the database state. The saved file is tracked using an ENV variable and
    can be used to restart the backend from the last known state
    """
    global _PUBSUB_STREAMING_THREAD
    _PUBSUB_STREAMING_THREAD = create_pubsub_streaming_thread()
    _PUBSUB_STREAMING_THREAD.start()
    try:
        while True:
            run_pending()
            time.sleep(1)
    except Exception as e:
        _LOGGER.error("There has been an unexpected exception, the backend will stop streaming data", exc_info=True)
    finally:
        # Killing all threads and saving the db state
        _LOGGER.warning("Stopping streaming process")
        stop_pubsub_streaming(_PUBSUB_STREAMING_OBJECT)
        filename = f'./data/exits/state_{datetime.now()}.csv'
        _LOGGER.warning(f"Saving state before exiting : {filename}")
        DATABASE.save_db_state(filename)

```

I believe it is worth noting that `run_backend` is ran in a specific thread.

Has anyone already ran into this kind of error ? I found nothing in here and already posted a question on stackoverflow but did not have any answers

Thanks!

**Comment by acocuzzo** [comment]
Hi @BarisicLuka 
Thanks for all the details, I will try to reproduce and get back to you with my findings.

**Comment by BarisicLuka** [comment]
Hi @acocuzzo ,

Thanks for looking into it. This error happens after a while (once or twice a day) and not as soon a the code is executed.

I dont know if that may help you but here is an example of logs showing that when the error occurs it prevents the streaming to restart when I ask for it (5 minutes after I stopped it). On the other hand once I kill the python process and re execute it it works fine for a while.

```
2022-08-05 15:07:52,974| Data pulling thread| 140661024470784| WARNING| backend.pubsub| start_pubsub_streaming()| L119 | Exception raised while pulling data, see below| call_trace=/home/.../backend/pubsub.py| L119 
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 50, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/.../venv/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/.../venv/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
  status = StatusCode.UNAVAILABLE
  details = "502:Bad Gateway"
  debug_error_string = "{"created":"@1659704872.958847109","description":"Error received from peer ipv4:108.177.15.95:443","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"502:Bad Gateway","grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 52, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 502:Bad Gateway

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../backend/pubsub.py", line 116, in start_pubsub_streaming
    pubsub_pulling_thread.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 1031, in _on_response
    self._send_lease_modacks(ack_id_gen, self.ack_deadline)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 977, in _send_lease_modacks
    self._dispatcher.modify_ack_deadline(items)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 356, in modify_ack_deadline
    ack_reqs_dict=ack_reqs_dict,
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 671, in send_unary_modack
    ack_deadline_seconds=deadline,
  File "/home/.../venv/lib/python3.7/site-packages/google/pubsub_v1/services/subscriber/client.py", line 1169, in modify_ack_deadline
    metadata=metadata,
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 210, in retry_target
    ) from last_exc
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 502:Bad Gateway
2022-08-05 15:07:52,976| Data pulling thread| 140661024470784| INFO  | backend.pubsub| stop_pubsub_streaming()| L131 | Stopping the streaming process ...| call_trace=/home/.../backend/pubsub.py| L131 
2022-08-05 15:07:52,977| Data pulling thread| 140661024470784| INFO  | backend.pubsub| start_pubsub_streaming()| L123 | Sleeping for 5 minutes before restarting the streaming| call_trace=/home/.../backend/pubsub.py| L123 
2022-08-05 15:08:00,517| Thread-5| 140661295675136| WARNING| backend.transitions_database| insert_buffered_inferences()| L123 | No buffered data to add to DB, check 
2022-08-05 15:12:53,056| Data pulling thread| 140661024470784| INFO  | backend.pubsub| start_pubsub_streaming()| L125 | Proceeding to streaming restart| call_trace=/home/.../backend/pubsub.py| L125 
2022-08-05 15:12:53,056| Data pulling thread| 140661024470784| INFO  | backend.pubsub| start_pubsub_streaming()| L115 | Starting streaming process| call_trace=/home/.../backend/pubsub.py| L115 
2022-08-05 15:12:53,056| Data pulling thread| 140661024470784| WARNING| backend.pubsub| start_pubsub_streaming()| L119 | Exception raised while pulling data, see below| call_trace=/home/.../backend/pubsub.py| L119 
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 50, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/.../venv/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/.../venv/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
  status = StatusCode.UNAVAILABLE
  details = "502:Bad Gateway"
  debug_error_string = "{"created":"@1659704872.958847109","description":"Error received from peer ipv4:108.177.15.95:443","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"502:Bad Gateway","grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 52, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 502:Bad Gateway

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../backend/pubsub.py", line 116, in start_pubsub_streaming
    pubsub_pulling_thread.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../backend/pubsub.py", line 120, in start_pubsub_streaming
    stop_pubsub_streaming(pubsub_pulling_thread)
  File "/home/.../backend/pubsub.py", line 133, in stop_pubsub_streaming
    pubsub_pulling_thread.result()  # Block until the shutdown is complete.
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../backend/pubsub.py", line 116, in start_pubsub_streaming
    pubsub_pulling_thread.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 1031, in _on_response
    self._send_lease_modacks(ack_id_gen, self.ack_deadline)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 977, in _send_lease_modacks
    self._dispatcher.modify_ack_deadline(items)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 356, in modify_ack_deadline
    ack_reqs_dict=ack_reqs_dict,
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 671, in send_unary_modack
    ack_deadline_seconds=deadline,
  File "/home/.../venv/lib/python3.7/site-packages/google/pubsub_v1/services/subscriber/client.py", line 1169, in modify_ack_deadline
    metadata=metadata,
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 210, in retry_target
    ) from last_exc
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 502:Bad Gateway
2022-08-05 15:12:53,056| Data pulling thread| 140661024470784| INFO  | backend.pubsub| stop_pubsub_streaming()| L131 | Stopping the streaming process ...| call_trace=/home/.../backend/pubsub.py| L131 
2022-08-05 15:12:53,057| Data pulling thread| 140661024470784| INFO  | backend.pubsub| start_pubsub_streaming()| L123 | Sleeping for 5 minutes before restarting the streaming| call_trace=/home/.../backend/pubsub.py| L123 
2022-08-05 15:13:11,081| AnyIO worker thread| 140660086654720| INFO  | backend.transitions_database| save_db_state()| L148 | Creating checkpoint ...| call_trace=/home/.../backend/transitions_database.py| L148 
2022-08-05 15:13:34,646| AnyIO worker thread| 140660086654720| DEBUG | backend.transitions_database| save_db_state()| L150 | Checkpoint created : ./data/api_checkpoints/recovery_5.csv| call_trace=/home/.../backend/transitions_database.py| L150 
2022-08-05 15:17:53,082| Data pulling thread| 140661024470784| INFO  | backend.pubsub| start_pubsub_streaming()| L125 | Proceeding to streaming restart| call_trace=/home/.../backend/pubsub.py| L125 
2022-08-05 15:17:53,082| Data pulling thread| 140661024470784| INFO  | backend.pubsub| start_pubsub_streaming()| L115 | Starting streaming process| call_trace=/home/.../backend/pubsub.py| L115 
2022-08-05 15:17:53,082| Data pulling thread| 140661024470784| WARNING| backend.pubsub| start_pubsub_streaming()| L119 | Exception raised while pulling data, see below| call_trace=/home/.../backend/pubsub.py| L119 
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 50, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/.../venv/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/.../venv/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
  status = StatusCode.UNAVAILABLE
  details = "502:Bad Gateway"
  debug_error_string = "{"created":"@1659704872.958847109","description":"Error received from peer ipv4:108.177.15.95:443","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"502:Bad Gateway","grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 52, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 502:Bad Gateway

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../backend/pubsub.py", line 116, in start_pubsub_streaming
    pubsub_pulling_thread.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../backend/pubsub.py", line 120, in start_pubsub_streaming
    stop_pubsub_streaming(pubsub_pulling_thread)
  File "/home/.../backend/pubsub.py", line 133, in stop_pubsub_streaming
    pubsub_pulling_thread.result()  # Block until the shutdown is complete.
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../backend/pubsub.py", line 116, in start_pubsub_streaming
    pubsub_pulling_thread.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../backend/pubsub.py", line 120, in start_pubsub_streaming
    stop_pubsub_streaming(pubsub_pulling_thread)
  File "/home/.../backend/pubsub.py", line 133, in stop_pubsub_streaming
    pubsub_pulling_thread.result()  # Block until the shutdown is complete.
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../backend/pubsub.py", line 116, in start_pubsub_streaming
    pubsub_pulling_thread.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 1031, in _on_response
    self._send_lease_modacks(ack_id_gen, self.ack_deadline)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 977, in _send_lease_modacks
    self._dispatcher.modify_ack_deadline(items)
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 356, in modify_ack_deadline
    ack_reqs_dict=ack_reqs_dict,
  File "/home/.../venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 671, in send_unary_modack
    ack_deadline_seconds=deadline,
  File "/home/.../venv/lib/python3.7/site-packages/google/pubsub_v1/services/subscriber/client.py", line 1169, in modify_ack_deadline
    metadata=metadata,
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/.../venv/lib/python3.7/site-packages/google/api_core/retry.py", line 210, in retry_target
    ) from last_exc
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 502:Bad Gateway
2022-08-05 15:17:53,083| Data pulling thread| 140661024470784| INFO  | backend.pubsub| stop_pubsub_streaming()| L131 | Stopping the streaming process ...| call_trace=/home/.../backend/pubsub.py| L131 
2022-08-05 15:17:53,083| Data pulling thread| 140661024470784| INFO  | backend.pubsub| start_pubsub_streaming()| L123 | Sleeping for 5 minutes before restarting the streaming| call_trace=/home/.../backend/pubsub.py| L123 
## Manually stopping and restarting the process here
2022-08-05 15:19:28,801| Data pulling thread| 139948455868160| INFO  | backend.pubsub| start_pubsub_streaming()| L115 | Starting streaming process| call_trace=/home/.../backend/pubsub.py| L115 
2022-08-05 15:20:00,835| Thread-5| 139948716922624| DEBUG | backend.transitions_database| insert_buffered_inferences()| L126 | Adding buffered inferences | call_trace=/home/.../backend/transitions_database.py| L126 
2022-08-05 15:20:00,968| Thread-5| 139948716922624| DEBUG | backend.transitions_database| insert_buffered_inferences()| L131 | Added 6729  in the Database| call_trace=/home/.../backend/transitions_database.py| L131 

```

Also I upgraded to `google-cloud-pubsub` version  2.13.4 but this happens

**Comment by acocuzzo** [comment]
Hi @BarisicLuka @kc-sn:
You can enable GRPC debug logs programmatically via: 
```
import os
os.environ['GRPC_VERBOSITY'] = "debug"
os.environ['GRPC_TRACE'] = "all"
```

**Comment by kc-sn** [comment]
> Hi @BarisicLuka @kc-sn: You can enable GRPC debug logs programmatically via:
> 
> ```
> import os
> os.environ['GRPC_VERBOSITY'] = "debug"
> os.environ['GRPC_TRACE'] = "all"
> ```

`tcp` is simply too verbose at the volume our system runs at, with:

```
  GRPC_VERBOSITY: "debug"
  GRPC_TRACE: "all,-tcp"
```

Datadog is reporting 502 bad gateways while the logging from GRPC doesn't report any 502s. I suspect datadog is instrumenting with [unary interceptor hooks](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/grpc/client_interceptor.py) -- where there is no logging traditionally. 

https://grpc.github.io/grpc/python/grpc.html#client-side-interceptor

```
StatusCode.UNAVAILABLE: 502:Bad Gateway
<traceback object at 0x7f5d94094280>
```
![image](https://user-images.githubusercontent.com/91487203/199823282-79f88835-9e61-4c80-bb26-0edee1c7a554.png)

**Comment by BarisicLuka** [comment]
Hi @acocuzzo @kc-sn 

The logs I provided were generated without any specific configuration / debugging options, tthe exceptions was raised by the `pubsub_v1.SubscriberClient`.
Do those 502s block the pulling mechanism ?

**Comment by kc-sn** [comment]
@BarisicLuka the errors we're seeing are not being propagated to the surface, but instead, are handled internally (and silently). The only reason we're seeing them is that datadog tracer has an interceptor on the GRPC library.
