### ISSUE TITLE
Cannot create BigQuery subscription

### ISSUE THREAD

**Issue by liberbey** [googleapis/python-pubsub#807]
#### Environment details

  - OS type and version: macOS Monterey
  - Python version: Python 3.10.5
  - pip version: pip 22.2.2
  - `google-cloud-pubsub` version: Version: 2.13.9

#### Steps to reproduce

Follow the "Create a BigQuery Subscription" tutorial in: https://cloud.google.com/pubsub/docs/create-subscription#pubsub_create_pull_subscription-python

#### Code example

```python
    def create_subscription(self, event_detail, subscriber, publisher):
        topic_path = publisher.topic_path(app_constants.PROJECT_ID, event_detail["topic_id"])
        subscription_path = subscriber.subscription_path(app_constants.PROJECT_ID, event_detail["subscription_id"])

        bigquery_config = pubsub_v1.types.BigQueryConfig(
            table=f"{app_constants.PROJECT_ID}.{app_constants.DATASET_ID}.{event_detail['table_id']}",
            write_metadata=True)

        # Wrap the subscriber in a 'with' block to automatically call close() to
        # close the underlying gRPC channel when done.
        with subscriber:
            subscription = subscriber.create_subscription(
                request={
                    "name": subscription_path,
                    "topic": topic_path,
                    "bigquery_config": bigquery_config,
                }
            )

        print(f"BigQuery subscription created: {subscription}.")
        print(f"Table for subscription is: ",
              f"{app_constants.PROJECT_ID}.{app_constants.DATASET_ID}.{event_detail['table_id']}")
```

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Request contains an invalid argument."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.20.74:443 {created_time:"2022-10-13T19:02:27.391945+03:00", grpc_status:3, grpc_message:"Request contains an invalid argument."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/app/app.py", line 40, in <module>
    pubsub_manager.run(event_details)
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/app/core/pubsub_structure_manager.py", line 52, in run
    self.create_subscription(event_detail, subscriber, publisher)
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/app/core/pubsub_structure_manager.py", line 102, in create_subscription
    subscription = subscriber.create_subscription(
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/venv/lib/python3.10/site-packages/google/pubsub_v1/services/subscriber/client.py", line 667, in create_subscription
    response = rpc(
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/venv/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/venv/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/venv/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/Users/liberbey/GIT/GitHub/cypher-proxy-server/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.

Process finished with exit code 1
```

As a note, when I delete _"bigquery_config": bigquery_config_ line, code works well and creates a pull subscription.

Also, debugger view of bigquery_config:

<img width="764" alt="Screen Shot 2022-10-13 at 19 06 57" src="https://user-images.githubusercontent.com/37846781/195648681-eb57c887-9bd3-417a-8c59-cd5bb46d3943.png">

Thanks a lot!

**Comment by liberbey** [comment]
Any improvement on this?

**Comment by acocuzzo** [comment]
@liberbey If you are receiving an Invalid Argument error, it's likely that the specified BigQuery table is incompatible, and does not contain the required metadata fields.
Please see the [BigQuery guide](https://cloud.google.com/pubsub/docs/bigquery):
Since you've selected false for "use_topic_schema," and the "write_metadata" please make sure your BigQuery table has the following parameters:
--
subscription_name | STRING Name of a subscription.
message_id | STRING ID of a message
publish_time | TIMESTAMP The time of publishing a message.
data | BYTES or STRINGThe message body.The data field is required for all destination BigQuery tables.
attributes | STRING A JSON object containing all message attributes. It also contains additional fields that are part of the Pub/Sub message including the ordering key, if present.

**Comment by liberbey** [comment]
Thanks!
