### ISSUE TITLE
DeadlineExceeded error when using subscriber.pull() on Apple Silicon

### ISSUE THREAD

**Issue by sloetjeswang** [googleapis/python-pubsub#916]
#### Environment details

  - OS type and version: Apple M2, 13.3.1 (a) (22E772610a)
  - Python version: Python 3.9.13
  - pip version: pip 22.3.1
  - `google-cloud-pubsub` version: 2.16.0
 
#### Description
When executing the script, an error occurs after a certain period of time, resulting in a DeadlineExceeded exception.

#### Steps to reproduce
  1. Import the necessary libraries and configure the Selenium driver options.
  2. Set up Pub/Sub subscription and initialize the driver.
  3. Load the product page and perform some actions.
  4. Start receiving messages using the subscriber.pull() method.
  5. Wait for some time until the DeadlineExceeded exception is raised.

#### Code example
```
# Import necessary libraries
from google.cloud import pubsub_v1
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import json
import time

# Configure the Selenium driver options
options = Options()
options.add_argument('--disable-gpu')
driver = webdriver.Chrome(options=options)

# Set up Pub/Sub subscription
project_id = 'price-extraction-project'
subscription_name = 'fp-subscription-NFL-zipcodes'
subscriber = pubsub_v1.SubscriberClient()
subscription_path = subscriber.subscription_path(project_id, subscription_name)
timeout = 5

# Load the product page and perform actions
...

# Start receiving messages (sync version)
while True: 
    pull_request = pubsub_v1.types.PullRequest(max_messages=1, subscription=subscription_path)
    pull_response = subscriber.pull(request=pull_request)
    callback(pull_response.received_messages[0])
```
#### Error Message
```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.DEADLINE_EXCEEDED
    details = "Deadline Exceeded"
    debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-05-09T20:09:48.584365-04:00", grpc_status:4}"
>
```
#### Stack trace
```
Traceback (most recent call last):
  File "~/example_script.py", line 132, in <module>
    pull_response = subscriber.pull(request=pull_request)
  File "~/opt/anaconda3/lib/python3.9/site-packages/google/pubsub_v1/services/subscriber/client.py", line 1495, in pull
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata)
  File "~/opt/anaconda3/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "~/opt/anaconda3/lib/python3.9/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(target, self._predicate, sleep_generator, self._timeout, on_error=on_error)
  File "~/opt/anaconda3/lib/python3.9/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "~/opt/anaconda3/lib/python3.9/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "~/opt/anaconda3/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
```

**Comment by acocuzzo** [comment]
1. Does the problem still occur with a higher deadline? It looks like you are setting the timeout to 5s.
2. How many messages are in the backlog when you receive this error?
3. How frequently are you pulling?

I would recommend filling an internal ticket if the issue persists with a higher deadline, if there are messages in the backlog, and if you are pulling frequently and the problem still occurs.

**Comment by acocuzzo** [comment]
Closing issue as no response.
