### ISSUE TITLE
PubSub emulator are broken

### ISSUE THREAD

**Issue by jefer94** [googleapis/python-pubsub#976]
#### Environment details

  - OS type and version: `Linux Lacey-Mosley 6.2.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 23:39:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
  - Python version: `3.11.4`
  - pip version: `23.0.1`
  - `google-cloud-pubsub` version: `2.18.1`

#### Steps to reproduce

  1. gcloud beta emulators pubsub start --project=xyz
  2. $(gcloud beta emulators pubsub env-init)
  3. emitter.py
  4. main.py

#### Code example

```python
# file1.py
import os
from typing import Any, Callable
from google.cloud import pubsub

from google.cloud.pubsub_v1.subscriber.message import Message

__all__ = ['Subscriber']

class Subscriber:
    def __init__(self):
        self.subscriber = pubsub.SubscriberClient()
 
    def subscribe(self, topic: str, callback: Callable[[Message], Any]):
        subscription = self.subscriber.topic_path(os.getenv('GOOGLE_CLOUD_PROJECT'), topic)
        self.subscription = self.subscriber.subscribe(subscription, callback)

    def desubscription(self):
        self.subscription.cancel()

# file2.py
import os
import json
from google.cloud import pubsub

__all__ = ['Publisher']

class Publisher:
    def __init__(self):
        self.publisher = pubsub.PublisherClient()


    def send(self, topic: str, data: dict):
        subscription = self.publisher.topic_path(os.getenv('GOOGLE_CLOUD_PROJECT'), topic)

        try:
            topic = self.publisher.create_topic(request={"name": subscription})
            
        except Exception:
            pass

        return self.publisher.publish(subscription, data=json.dumps(data).encode('utf-8'))

# emitter.py
from dotenv import load_dotenv

load_dotenv() 

import os
from google.cloud import pubsub

from .services.google_cloud import Publisher


p = Publisher()
message_future = p.send('test', {'aa': 2})

print(message_future.result())

# main.py
@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    def callback(message: Message):
        o = json.loads(message.data.decode("utf-8"))
        print(o)
        try:
            asyncio.create_task(websocket.send_json(o))
        except:
            ...
        message.ack()

    await websocket.accept()
    await websocket.send_json({'accepted': True})
    await websocket.receive()

    subscriber = Subscriber()
    subscriber.subscribe('test', callback)
```

#### Stack trace
```
(.venv) ➜  emit gcloud beta emulators pubsub start --project=xyz
Executing: /home/jefer/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=::1 --port=8012
[pubsub] This is the Google Pub/Sub fake.
[pubsub] Implementation may be incomplete or differ from the real system.
[pubsub] Aug 09, 2023 1:59:33 AM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
[pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
[pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[pubsub] Aug 09, 2023 1:59:33 AM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: Server started, listening on 8012
[pubsub] Aug 09, 2023 2:00:04 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected HTTP/2 connection.
[pubsub] Aug 09, 2023 2:01:25 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected HTTP/2 connection.
[pubsub] Exception in thread "pool-1-thread-1" java.lang.NullPointerException
[pubsub]        at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
[pubsub]        at com.google.cloud.pubsub.testing.v1.FakePubsubServer$StreamingPullPusher.run(FakePubsubServer.java:1747)
[pubsub]        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[pubsub]        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[pubsub]        at java.base/java.lang.Thread.run(Thread.java:829)
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jefer94** [comment]
I don't know, this was first version I used, if you provide me the command to install other version I can test it

**Comment by jefer94** [comment]
I'm using `openjdk-11-jre`

**Comment by mishridaga** [comment]
@jefer94 in your subscribe code you are attempting to call subscribe on a "topic" instead of a subscription: 

```python
    def subscribe(self, topic: str, callback: Callable[[Message], Any]):
        subscription = self.subscriber.topic_path(os.getenv('GOOGLE_CLOUD_PROJECT'), topic)
        self.subscription = self.subscriber.subscribe(subscription, callback)
```

Please reference https://github.com/googleapis/python-pubsub/blob/main/samples/snippets/subscriber.py for some examples of how to setup a subscriber and pull messages from Pub/Sub. You may also find the tutorial in https://cloud.google.com/pubsub/docs/emulator#using_the_emulator helpful!

**Comment by jefer94** [comment]
I made a few changes to fix that error, but anyway, if I used `topic_path` instead of `subscription_path`, this must raise an exception, now I'm getting the messages through websocket and all looks fine
