### ISSUE TITLE
504 Deadline Exceeded when Publishing

### ISSUE THREAD

**Issue by OscarVanL** [googleapis/python-pubsub#994]
#### Environment details

  - OS type and version: Debian Bullseye container running on Ubuntu 18.04 host
  - Python version: `python --version`: 3.9
  - pip version: `pip --version`: 23.2.1
  - `google-cloud-pubsub` version: `pip show google-cloud-pubsub`: `2.18.4` (I had the same issue on `2.3.0` too, updating did not resolve it)

#### Steps to reproduce

When publishing PubSub messages, a high proportion fail with timeout errors (from my measurements, about 9% fail).

#### Code example

My use-case is incredibly simple. I have a CRUD app that publishes cache invalidation messages via PubSub when something is created/updated/deleted. There's a callback that handles logging successes or failures.

As you can see, each payload is only a UUID, so very small.

```python
class PubSubClient:
    def __init__(self, project_id: str):
        self.project_id = project_id
        self.publisher = pubsub_v1.PublisherClient()
        self.cache_invalidation_topic = pubsub_v1.PublisherClient.topic_path(
            self.project_id, 'my-topic-name'
        )

    def get_callback(self, uuid):
        start = datetime.datetime.now()

        def callback(f):
            duration = datetime.datetime.now() - start
            try:
                result = f.result()
                logging.debug(f"Successfully published {uuid} to pubsub in {duration.seconds} sec: {result}")
            except:
                logging.exception(f"Failed to publish {uuid} to pubsub in {duration.seconds} sec")

        return callback

    def invalidate_cache(self, uuid: str):
        logging.info(f"Publishing to pubsub to invalidate cache for {uuid}")
        future = self.publisher.publish(self.cache_invalidation_topic, uuid.encode("utf-8"))
        future.add_done_callback(self.get_callback(uuid))

# The client gets initialised as a global variable, which then gets imported in various places
pubsub_client = PubSubClient(settings.GCP_PROJECT_ID)
```

This `PubSubClient` gets initialised at service startup. I run 12 workers via uWSGI, so in total there will be 12 PublisherClients each on different threads.

The code gets called from a Django REST API handler:

```python
from my.package.path import pubsub_client

def update_thing(request):
    # CRUD stuff
    thing.save()
    pubsub_client.invalidate_cache(thing.uuid)

    return HttpResponse(status=201)
```

#### Stack trace
```
Failed to publish <REDACTED> to pubsub in 1165 sec
Traceback (most recent call last):
  File "/service/venv/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/service/venv/lib/python3.9/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/service/venv/lib/python3.9/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
tstatus = StatusCode.DEADLINE_EXCEEDED
tdetails = "Deadline Exceeded"
tdebug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-09-12T19:45:10.511476452+00:00", grpc_status:4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/service/venv/lib/python3.9/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/service/venv/lib/python3.9/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/service/venv/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/my/service/pubsub_client.py", line 23, in callback
    result = f.result()
  File "/service/venv/lib/python3.9/site-packages/google/cloud/pubsub_v1/publisher/futures.py", line 66, in result
    return super().result(timeout=timeout)
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/my/service/pubsub_client.py", line 23, in callback
    result = f.result()
  File "/service/venv/lib/python3.9/site-packages/google/cloud/pubsub_v1/publisher/futures.py", line 66, in result
    return super().result(timeout=timeout)
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/service/venv/lib/python3.9/site-packages/google/cloud/pubsub_v1/publisher/_batch/thread.py", line 274, in _commit
    response = self._client._gapic_publish(
  File "/service/venv/lib/python3.9/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 267, in _gapic_publish
    return super().publish(*args, **kwargs)
  File "/service/venv/lib/python3.9/site-packages/google/pubsub_v1/services/publisher/client.py", line 831, in publish
    response = rpc(
  File "/service/venv/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/service/venv/lib/python3.9/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/service/venv/lib/python3.9/site-packages/google/api_core/retry.py", line 207, in retry_target
    raise exceptions.RetryError(
google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling target function, last exception: 504 Deadline Exceeded
```

**Comment by liuyunnnn** [comment]
Hi @OscarVanL 

Can you check this [flow control](https://cloud.google.com/pubsub/docs/publisher#flow_control) page and see if it works on your case?

**Comment by OscarVanL** [comment]
I believe I found the fix for my issue. I applied it and have not observed any errors for 24 hours.

In our web app, we use uWSGI to have multiple workers (similar to gunicorn).

By default, the uWSGI config opts to disable the python GIL / threading. See [here](https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html):
> By default the Python plugin does not initialize the GIL. This means your app-generated threads will not run. If you need threads, remember to enable them with enable-threads. Running uWSGI in multithreading mode (with the threads options) will automatically enable threading support. This “strange” default behaviour is for performance reasons, no shame in that.

I expect this interferes with the PubSub background thread that performs batch publishing.

My fix was to modify my uWSGI config to enable threading.

I also added this check in my application at startup, maybe you could consider adding a similar check to the PubSub library, or at least log a warning in this scenario?
```
    @staticmethod
    def _require_uwsgi_threading():
        uwsgi_module = sys.modules.get('uwsgi')
        if not getattr(uwsgi_module, 'has_threads', True):
            raise RuntimeError(
                'The scheduler seems to be running under uWSGI, but threads have '
                'been disabled. You must run uWSGI with the --enable-threads '
                'option for the scheduler to work.'
            )
```

**Comment by liuyunnnn** [comment]
Thanks for finding this! We actually already documented it over [here](https://github.com/googleapis/python-pubsub/blob/b1a2898913c3eb1c2ec72cdaddaa8a9da91a9558/docs/pubsub/publisher/index.rst#L67)(Batching section). We will consider adding a check or log a warning in the future.

**Comment by OscarVanL** [comment]
Thanks, I guess we missed this one because we were not intentionally running in an environment with threading disabled. (Unfortunately this is a strange default for uWSGI.)
